import type { AIProvider, AIProviderRequest, AIProviderResult } from "../types";

interface GroqErrorResponse {
  error?: {
    message?: string;
  };
}

interface GroqSuccessResponse {
  choices?: Array<{
    message?: {
      content?: string;
    };
  }>;
}

export class GroqProvider implements AIProvider {
  private readonly apiKey: string;
  private readonly endpoint: string;

  constructor(apiKey: string, endpoint = "https://api.groq.com/openai/v1/chat/completions") {
    this.apiKey = apiKey;
    this.endpoint = endpoint;
  }

  async createCompletion(input: AIProviderRequest): Promise<AIProviderResult> {
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), input.timeoutMs ?? 15000);

    try {
      const response = await fetch(this.endpoint, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${this.apiKey}`,
        },
        body: JSON.stringify({
          model: input.model,
          messages: input.messages,
          temperature: input.temperature ?? 0.2,
          max_tokens: input.maxTokens ?? 700,
          stream: false,
        }),
        signal: controller.signal,
      });

      if (!response.ok) {
        const data = (await response.json().catch(() => ({}))) as GroqErrorResponse;
        const detail = data.error?.message || "Unknown Groq error";
        const message = response.status === 429
          ? "Too many requests right now. Please wait a moment and try again."
          : `Groq request failed (${response.status}): ${detail}`;
        throw new Error(message);
      }

      const data = (await response.json()) as GroqSuccessResponse;
      const reply = data.choices?.[0]?.message?.content?.trim();

      if (!reply) {
        throw new Error("No response generated by AI provider.");
      }

      return { reply };
    } catch (error) {
      if (error instanceof Error && error.name === "AbortError") {
        throw new Error("The assistant timed out. Please try again.");
      }
      throw error;
    } finally {
      clearTimeout(timeoutId);
    }
  }
}
